### ISSUE TITLE
Opacity does not work anymore

### ISSUE THREAD

**Issue by T94T** [joshmarinacci/aminogfx-gl#12] opened 2017-08-04 19:08 UTC
First of all, I want to say thanks for this great repo. Some months ago I wrote a little program with some transparency on the stage object. Today I updated the module and noticed that some methods changed. Finally I got it working again.

Unfortunately the opacity() method seems to not work as expected. Background color remains solid.
```
gfx.start(function(err){
    if (err) {
        console.log('Start failed: ' + err.message);
        return;
    }
    this.fill("#FF0000");
    this.opacity(0.1);
    //...
}
```

**Comment by cbratschi** [comment] 2017-08-06 11:52
Duplicate of https://github.com/joshmarinacci/aminogfx-gl/issues/7

**Closed as completed** 2017-08-06 11:52 UTC
